apiVersion: v1
kind: ConfigMap
metadata:
  name: recommendation-api-config
  namespace: ecommerce-recommendation
  labels:
    app: recommendation-api
data:
  LOG_LEVEL: "INFO"
  MODEL_VERSION: "v1-dummy"
  WORKERS: "4"
  HOST: "0.0.0.0"
  PORT: "8000"

